export const data = [
  { id: 1, image: "https://i.ibb.co/zxVfY0j/dpshat.jpg" },
  { id: 2, image: "https://i.ibb.co/HV1tYbq/aman.jpg" },
  { id: 3, image: "https://i.ibb.co/mqtC1vX/anya.jpg" },
  { id: 4, image: "https://i.ibb.co/4WpcDfw/ashish.jpg" },
  { id: 5, image: "https://i.ibb.co/S32gPdB/chandu.jpg" },
  { id: 6, image: "https://i.ibb.co/m01XypM/me.jpg" },
  { id: 7, image: "https://i.ibb.co/rwz4LTy/paraj.jpg" },
  { id: 8, image: "https://i.ibb.co/rpLbHcp/pepsi.jpg" },
  { id: 9, image: "https://i.ibb.co/JjLzwFb/radhe.jpg" },
  { id: 10, image: "https://i.ibb.co/tXnBDG5/sangam.jpg" },
  { id: 11, image: "https://i.ibb.co/JKMysns/sapi.jpg" },
  { id: 12, image: "https://i.ibb.co/RpGB7mf/tushya.jpg" },
  { id: 13, image: "https://i.ibb.co/k57hXzv/ujya.jpg" },
  { id: 14, image: "https://i.ibb.co/7nrV4KY/vaishi.jpg" },
  { id: 15, image: "https://i.ibb.co/JHZ0X24/logo.jpg" },
];
