export const data = [
  { id: 1, image: "https://i.ibb.co/Chs7Gfc/dpshat.png" },
  { id: 2, image: "https://i.ibb.co/1MbsV6v/aman.png" },
  { id: 3, image: "https://i.ibb.co/wQsScd1/anya.png" },
  { id: 4, image: "https://i.ibb.co/tYGY3vq/ashish.png" },
  { id: 5, image: "https://i.ibb.co/YWjjky9/chandu.png" },
  { id: 6, image: "https://i.ibb.co/b2XKpnD/me.png" },
  { id: 7, image: "https://i.ibb.co/SwRj181/paraj.png" },
  { id: 8, image: "https://i.ibb.co/gPdbj4y/pepsi.png" },
  { id: 9, image: "https://i.ibb.co/FV6WPBb/radhe.png" },
  { id: 10, image: "https://i.ibb.co/M6TYhrt/sangam.png" },
  { id: 11, image: "https://i.ibb.co/JKMysns/sapi.jpg" },
  { id: 12, image: "https://i.ibb.co/wJHZYjz/sapi.png" },
  { id: 13, image: "https://i.ibb.co/fSPs1f0/ujya.png" },
  { id: 14, image: "https://i.ibb.co/wNv460B/vaishi.png" },
  { id: 15, image: "https://i.ibb.co/SPKw7RT/logo.png" },
];
